# Generated by Django 5.1.3 on 2024-11-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
