# Generated by Django 5.1.3 on 2024-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='card_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
