# Generated by Django 5.1.3 on 2024-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0004_speaker_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='card_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
