# Generated by Django 5.1.3 on 2024-11-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0005_alter_speaker_card_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('card_num', models.IntegerField()),
            ],
        ),
    ]
